/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer tous les utilisateurs */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Créer un nouvel utilisateur */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer un utilisateur par ID */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Supprimer un utilisateur */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Mettre à jour un utilisateur */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer le profil connecté */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer toutes les annonces */
        get: operations["AnnouncementsController_findAll"];
        put?: never;
        /** Créer une annonce */
        post: operations["AnnouncementsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer une annonce par ID */
        get: operations["AnnouncementsController_findOne"];
        put?: never;
        post?: never;
        /** Supprimer une annonce */
        delete: operations["AnnouncementsController_remove"];
        options?: never;
        head?: never;
        /** Mettre à jour une annonce */
        patch: operations["AnnouncementsController_update"];
        trace?: never;
    };
    "/neighbourhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer tous les quartiers */
        get: operations["NeighbourhoodsController_findAll"];
        put?: never;
        /** Créer un quartier */
        post: operations["NeighbourhoodsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neighbourhoods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer un quartier par ID */
        get: operations["NeighbourhoodsController_findOne"];
        put?: never;
        post?: never;
        /** Supprimer un quartier */
        delete: operations["NeighbourhoodsController_remove"];
        options?: never;
        head?: never;
        /** Mettre à jour un quartier */
        patch: operations["NeighbourhoodsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            _id: string;
            /** @example john.doe@email.com */
            email: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /**
             * @default habitant
             * @enum {string}
             */
            role: "habitant" | "moderateur" | "admin";
            /** @example 64a1f2c3e4b5f6a7b8c9d0e2 */
            neighbourhoodId?: string;
            /** @example 0 */
            points: number;
            /** @example true */
            isActive: boolean;
            /**
             * @default fr
             * @enum {string}
             */
            lang: "fr" | "en";
            /** Format: date-time */
            createdAt: string;
        };
        CreateUserDto: {
            /** @example john.doe@email.com */
            email: string;
            /** @example MonMotDePasse1! */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /**
             * @default habitant
             * @enum {string}
             */
            role: "habitant" | "moderateur" | "admin";
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            neighbourhoodId?: string;
            /** @example 0 */
            points?: number;
            /**
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @default fr
             * @enum {string}
             */
            lang: "fr" | "en";
        };
        UpdateUserDto: {
            /** @example john.doe@email.com */
            email?: string;
            /** @example NouveauMdp1! */
            password?: string;
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @enum {string} */
            lang?: "fr" | "en";
            /** @example true */
            isActive?: boolean;
        };
        SignupDto: {
            /** @example john.doe@email.com */
            email: string;
            /** @example MonMotDePasse1! */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /**
             * @default fr
             * @enum {string}
             */
            lang: "fr" | "en";
        };
        SigninDto: {
            /** @example john.doe@gmail.com */
            email: string;
            /** @example MonMotDePasse1! */
            password: string;
        };
        CreateAnnouncementDto: {
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            authorId: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e2 */
            neighbourhoodId: string;
            /** @example Tonte de pelouse */
            title: string;
            /** @example Je propose de tondre la pelouse de mes voisins. */
            description: string;
            /**
             * @example offer
             * @enum {string}
             */
            type: "offer" | "request";
            /**
             * @default false
             * @example false
             */
            isPaid: boolean;
            /**
             * @default 0
             * @example 10
             */
            points: number;
            /**
             * @default open
             * @enum {string}
             */
            status: "open" | "accepted" | "done";
        };
        Announcement: {
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            id: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e2 */
            authorId: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e3 */
            neighbourhoodId: string;
            /** @example Tonte de pelouse */
            title: string;
            /** @example Je propose de tondre la pelouse de mes voisins. */
            description: string;
            /**
             * @example offer
             * @enum {string}
             */
            type: "offer" | "request";
            /**
             * @default false
             * @example false
             */
            isPaid: boolean;
            /**
             * @default 0
             * @example 0
             */
            points: number;
            /**
             * @default open
             * @enum {string}
             */
            status: "open" | "accepted" | "done";
            /** @example 64a1f2c3e4b5f6a7b8c9d0e4 */
            acceptedBy?: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e5 */
            contractId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateAnnouncementDto: {
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            authorId?: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e2 */
            neighbourhoodId?: string;
            /** @example Tonte de pelouse */
            title?: string;
            /** @example Je propose de tondre la pelouse de mes voisins. */
            description?: string;
            /** @enum {string} */
            type?: "offer" | "request";
            /** @example false */
            isPaid?: boolean;
            /** @example 10 */
            points?: number;
            /** @enum {string} */
            status?: "open" | "accepted" | "done";
            /** @example 64a1f2c3e4b5f6a7b8c9d0e3 */
            acceptedBy?: string;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e4 */
            contractId?: string;
        };
        CreateNeighbourhoodDto: {
            /** @example Montmartre */
            name: string;
            /**
             * @example {
             *       "type": "Polygon",
             *       "coordinates": [
             *         [
             *           [
             *             2.33,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.88
             *           ]
             *         ]
             *       ]
             *     }
             */
            geometry?: Record<string, never>;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            createdBy: string;
        };
        Neighbourhood: {
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            id: string;
            /** @example Montmartre */
            name: string;
            /**
             * @example {
             *       "type": "Polygon",
             *       "coordinates": [
             *         [
             *           [
             *             2.33,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.88
             *           ]
             *         ]
             *       ]
             *     }
             */
            geometry?: Record<string, never>;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e2 */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateNeighbourhoodDto: {
            /** @example Belleville */
            name?: string;
            /**
             * @example {
             *       "type": "Polygon",
             *       "coordinates": [
             *         [
             *           [
             *             2.33,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.88
             *           ],
             *           [
             *             2.34,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.89
             *           ],
             *           [
             *             2.33,
             *             48.88
             *           ]
             *         ]
             *       ]
             *     }
             */
            geometry?: Record<string, never>;
            /** @example 64a1f2c3e4b5f6a7b8c9d0e1 */
            createdBy?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Données invalides. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'utilisateur */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Utilisateur non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'utilisateur */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilisateur supprimé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Utilisateur non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'utilisateur */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Utilisateur non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SigninDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Non authentifié. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnnouncementsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"][];
                };
            };
        };
    };
    AnnouncementsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnnouncementDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            /** @description Données invalides. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnnouncementsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'annonce */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            /** @description Annonce non trouvée. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnnouncementsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'annonce */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Annonce supprimée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Annonce non trouvée. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnnouncementsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB de l'annonce */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAnnouncementDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            /** @description Annonce non trouvée. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeighbourhoodsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbourhood"][];
                };
            };
        };
    };
    NeighbourhoodsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNeighbourhoodDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbourhood"];
                };
            };
            /** @description Données invalides. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeighbourhoodsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB du quartier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbourhood"];
                };
            };
            /** @description Quartier non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeighbourhoodsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB du quartier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quartier supprimé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Quartier non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NeighbourhoodsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ObjectId MongoDB du quartier */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNeighbourhoodDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbourhood"];
                };
            };
            /** @description Quartier non trouvé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
