services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: hoodly_api_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - hoodly

  mongodb:
    image: mongo:7
    container_name: hoodly_mongo_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hoodly
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - hoodly

  mongo-express:
    image: mongo-express:latest
    container_name: hoodly_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - hoodly

volumes:
  mongo_dev_data:
    driver: local

networks:
  hoodly:
    external: true
